### ISSUE TITLE
Training MLH off of result MLHZ and prediction MLHR as MLHRZ_RATIO

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lczero-training#123]
_**EDIT: I've edited the proposed function to include a limit convergence rate for the sigmoid function.**_
The idea is to include searched-M-at-root and actual MLH related to the result in a ratio for training MLH, much like how Q-ratio currently takes Z and Q to train W,D,L.

One issue with a pure, unfettered ratio between the two may be asking for disaster, as when the result nears, the actual result should be more certain and accurate (at least, early in training) than the searched-M-at-root.

This might be a tough 4-multivariable tune, so some of these factors can be eliminated if need be--however, each of the factors should improve the fidelity of the end product. (I consider ω and θ of highest priority.) 

We can use MLHZ ≥ 1 sigmoid function (with optional negative parameters ω, ψ) to create the moves-left based ratio:
``MLHRZ_RATIO(ω,C,ψ,θ)``
``MLHRZ_RATIO=ω/(1+e^C(MLHZ-ψ))+θ``

where the limit is 
``0 < lim (MLHRZ_RATIO=ω/(1+e^C(MLHZ-ψ))+θ) < 1``
``MLHZ->+∞ and MLHZ->0``
or for simplicity (ignoring the allowed properties by C and ψ):
``0 < ω+θ < 1``

C is a convergence factor that adjusts the MLHZ-related convergence to the limits of the sigmoid output.

ω is a -1+θ < ω < 1-θ bounded coefficient which modulates the height of the sigmoid curve. 

Where ψ is (chosen as it is a high-level pun for left-right "psichology") a coefficient to shift the sigmoid curve right if positive, and left if negative.

θ up/downshifts the sigmoid function, bounded (but not strictly bounded because a lower/upper division of the sigmoid may be cut off before MLHZ≥1) by 0 < θ < 1

**Comment by TesseractA** [comment]
Exa also commented in the lc0 discord about potentially combining all the value heads into one value through a ratio; though this is obviously absurd, it might not be a terrible experiment from a neural-network enthusiast standpoint.

**Comment by TesseractA** [comment]
Closing as I will be working on this soon, so no need to draw eyes until its actually done :)

**Comment by Dboingue** [comment]
MLHZ

**Comment by TesseractA** [comment]
MLH = Moves Left Head, a recent addition by kiudee to used to estimate (and for search, to reduce) the number of moves remaining until the end of a game.

MLHZ is as if it were the moves left Z (as in, the actual amount of moves left before a game ends) and MLHR is moves left head searched from root that was derived from the engine's search+network during the game. MLHRZ-ratio trains MLH off of MLHR and MLHZ.
