### ISSUE TITLE
leelalogs writing in train_input folder bug on colab

### ISSUE THREAD

**Issue by teck45** [LeelaChessZero/lczero-training#154]
I encountered strange bug related to leelalogs. Train.py created leelalogs folder in folder where training chunks are! Saw it with another guy who tried colab training and then encountered it myself...
My train.py and lczero-training folder are on google drive. Unpacked train and test chunks folders are on colab hdd. It worked fine. Script used chunks from colab hdd, saved leelalogs to lczero/tf/leelalogs folder on google drive. As I know this path is hardcoded inside train.py, right? I feel that sometimes google drive mount can fail and train.py wants to write somethere and write it in input! Worst possible place. Then it tries to parse this as chunks and training fails... It should write it in some another place :)

**Comment by Tilps** [comment]
Training saves leela logs into a directory relative to the current working directory.  If you start train.py while the current working directory is the training data folder you are going to have a bad time.

**Comment by teck45** [comment]
This is strange. I can launch train.py with cd /path/ to tf && train.py. I done it like this before. And this time I used path/train.py to launch. Ok its a strange feature.. Hopefully I will not encounter this again >.< But lellalogs path in yaml would have been much better =)

**Comment by teck45** [comment]
looks working fine with cd /path/ to tf && train.py pattern.
