### ISSUE TITLE
Split script trim assumes that test and train are correct ratios before starting.

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lczero-training#21]
The trim step always removes a constant number of oldest entries from test and a different constant number from train.  If the initial state is unbalanced, this inbalance continues to exist.

Probably as a first step before running diff to to calculate which games need to be brought over, there should be a balancing trim - which instead of trimming by a constant amount, trims to ensure both test and train are no larger than the intended total, and that even if smaller, they have the correct ratio.

**Comment by Error323** [comment]
I think it's a safe assumption (in general) that split is prepared correctly. See `init.sh`

**Comment by Tilps** [comment]
I think this has been fixed now.
