### ISSUE TITLE
Question about the meaning of input shape and output shape

### ISSUE THREAD

**Issue by tianyu-z** [LeelaChessZero/lczero-training#223]
The input shape plane is (batch_size, 112, 8, 8) and the output shape is (batch_size, 1858). What is the meaning of 112 and the 1858? In other words, what should I input to the model and what I should expect the model to output? Thank you!

**Comment by mooskagh** [comment]
Closing as it was discussed in the chat.

**Comment by Dboingue** [comment]
chat not being shared. bummer.  I learn much from discussions.. It looked like a good starter here, going for the jugular of chess interpretable information.   Not that I am sure to understand where that is meant to go, but at least I enjoyed the structuring of the starting post.   Sounds like good language for use documentation. Not that I would be working for that. just saying..  Sounds like well informed yet clarifying notions to share outside of GitHub and chats.
